version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "01:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: setuptools
    versions:
    - "> 57.5.0"