name: Push

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    if: github.repository == 'LuisAlejandro/pypicontents'
    strategy:
      matrix:
        include:
          - python-version: "3.8"
            toxenv: "py38"
          - python-version: "3.9"
            toxenv: "py39"
          - python-version: "3.10"
            toxenv: "py310"
          - python-version: "3.11.0-alpha.5"
            toxenv: "py311"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: develop
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installing dependencies
        run: |
          sudo apt-get install libxml2-dev libxslt-dev
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Measuring coverage
        env:
          TOXENV: ${{ matrix.toxenv }}
          PYTHON_VERSION: ${{ matrix.python-version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tox -e ${TOXENV}
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: run-py${{ matrix.python-version }}
          path-to-lcov: ./.lcov
          parallel: true
      - name: Functional test
        env:
          TOXENV: ${{ matrix.toxenv }}
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
          if [ "${TOXENV}" == "py311" ]; then
            PYTHON_VERSION="3.11"
          fi
          docker run -v ${PWD}:${PWD} -w ${PWD} \
              dockershelf/python:${PYTHON_VERSION} bash -c \
              "pip install . && \
              pypicontents pypi -o data/0-9/pypi.json -f logs/0-9/pypi.log -R 0-9"
          docker run -v ${PWD}:${PWD} -w ${PWD} \
              dockershelf/python:${PYTHON_VERSION} bash -c \
              "pip install . && \
              pypicontents stdlib -o stdlib/${PYTHON_VERSION}/stdlib.json"

  finish:
    name: Finish
    runs-on: ubuntu-20.04
    if: github.repository == 'LuisAlejandro/pypicontents'
    needs: build
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true